"""Write measured results, distinguishing inherited missing origins from newly observed ones."""
from pathlib import Path
import json,collections,datetime
R=Path(__file__).resolve().parents[1];D=R/'data-sources/residuals-v19-20260915';S=R/'data-sources/sentetsu-v19-20260915'
def read(p):return json.loads(p.read_text())
ledger=read(S/'ledger.json');walk=read(S/'walking-correspondence.json');ref=read(D/'reference-connections-review.json');app=read(S/'application-verification.json');timing=read(D/'timing.json');study=read(R/'src/data/boarding-guide-study.json');idx=read(R/'src/data/boarding-walk-study/index.json')['stops']
confirmed=[p for g in ledger['pairs'] for p in g['points'] if p['status']=='机上確認済み'];held=[p for g in ledger['pairs'] for p in g['points'] if p['status']=='保留'];resolved=[p for p in ref['points'] if p['resolved']];now=datetime.datetime.now(datetime.timezone.utc);mins=(now-datetime.datetime.fromisoformat(timing['started_at'])).total_seconds()/60
summary={'baseline_commit':timing['baseline'],'started_at':timing['started_at'],'implementation_report_at':now.isoformat(),'elapsed_minutes_excluding_initial_environment_check':round(mins,1),'sentetsu_observed_originals':ledger['summary'],'new_calculated_walks':sum(bool(p['file']) for p in walk['points']),'new_uncomputed_walks':sum(not p['file'] for p in walk['points']),'existing_reference_walks_resolved_reused':len(resolved),'existing_reference_walks_still_held':len(ref['points'])-len(resolved),'original_128_missing_remaining':sum(not idx[p['id']].get('file') for p in read(D/'missing-128-review.json')['points']),'recalculated_existing_walks':0,'active_calculated_walks_total':sum(bool(e.get('file')) for e in idx.values()),'total_uncomputed_index_entries':sum(not e.get('file') for e in idx.values()),'coordinate_only_held_originals':len(read(S/'coordinate-only-holds.json')),'observed_boarding_originals_added_to_map':len(confirmed)+len(held),'walking_calculation_seconds':read(S/'bake-receipt-first.json')['seconds']+read(S/'bake-receipt.json')['seconds'],'browser_checked':False,'device_checked':False,'safari_checked':False,'field_checked':False}
(D/'result-summary.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2)+'\n')
lines=['# v19 追加資料と県内残件対応','',f"v18 {timing['baseline']} の原本・判定を保持した差分。全保留の解消ではありません。",'', '## 追加提示された船木鉄道ODPTリンク','', 'https://ckan.odpt.org/dataset/odpt_sentetsu_bus_all_lines/resource/eccb7d07-d0af-4aa8-96f4-3e2c55ba87ed','', '今回追加で確認。リアルタイム情報・Protocol Buffers・公共交通オープンデータ基本ライセンス。原バイナリ未取得であり、v18で位置・方面の直接根拠に採用済みだったとは報告しない。ページ自体には原乗り場座標・停車順の対応がない。公式せんナビの別公開資料を実取得して今回の照合に使用。認証付きGTFSへの迂回は行っていない。','', '## 今回確認した乗り場','',f"船木鉄道の取得対象は2026-09-15の小野田線16便に対応する公開情報。{len(confirmed)}原点は机上整合、{len(held)}原点は保留。全曜日・全路線網羅としない。末尾の数字を公式の乗り場番号として扱わない。",'', '|地域・停留所|原ID・原座標|乗る方面|根拠|徒歩圏・施設|','|---|---|---|---|---|']
for p in confirmed:
 id=p['id'];hub=next(f for f in study['hub_points'] if f['id']==id);es=p['occurrences'];w=next(w for w in walk['points'] if w['id']==id);a=next(a for a in app['new_walking_results'] if a['id']==id)
 heads=' / '.join(sorted({e['headsign'] for e in es}));e=es[0];proof=f"{e['previous_stop_name']}→当点→{e['next_stop_name']}。公式経路区間{e['official_map_section']}、道路{e['way_id']}、進行方位{e['heading_deg']}°、左側{e['signed_left_m']}m。"+('図の折れを個別確認、40/60/80m区間の車道方向とも照合。' if e.get('individual_section_review') else '')
 lines.append('|'+ '|'.join([hub['properties']['city']+'・'+p['name'],id+' '+str(p['original_coordinates']),heads,proof,w['status']+'。5/10/15分施設 '+str(a.get('counts_5_10_15','未計算'))])+'|')
lines+=['','原点と方面：公式サイト https://www.sentetsu.jp/scheduled-bus/sennavi-guidance/ が直接案内する https://sentetsu.busplus.jp/ の公開情報。乗車検索のpickup.stop_idとheadsign、tripdetailの前後停車順、busstopの同じstop_id原座標を保持。','経路：公式 https://sentetsu.bustei.net/buslocation/ の描画線。便別GTFS shapeではない。座標が完全一致する線分接続から分岐のない区間だけを抽出し、前後原点を同一区間で一意に順序付けられる場合のみ道路照合。最短経路・近接連結・循環方向の推測は行わない。','道路：完全属性付きOSMを取得。個別図は原資料の座標を重ねた検討図で、公式印刷図や実ブラウザーのスクリーンショットではない。','', '## 既存徒歩圏の対応を解消した5原点','']
for p in resolved:
 g=study['guides'][p['id']];lines.append('- '+(g.get('stop_name') or next(f['properties']['name'] for f in read(R/'public/data/review-stops.geojson')['features'] if f['id']==p['id']))+' / '+p['id']+' / '+g['summary']+'：同じ道路側の明示footway=sidewalk、接続区間の収録車道・障壁横断なし。既存原点・計算を変更せず再利用。')
lines+=['',f"新規計算{summary['new_calculated_walks']}、既存再計算0、今回対応を解消して再利用5。既存1143徒歩圏ファイルとv18有効indexは変更しない。",'', '## 未計算128地点と残件','', '地図には乗車記録を得た74原点を追加し、7原点は確認済み、67原点は道路側対応保留として表示。別に座標だけ取得した7原点は乗車記録不足としてcoordinate-only-holds.jsonに保存し、地図の方向別乗り場には割り当てていない。',f"従来128地点は{summary['original_128_missing_remaining']}地点のまま。内訳は位置・道路側机上確認50、既存公式乗り場座標12、位置対応保留66。全件をmissing-128-review.jsonで照合し、追加道路根拠のある再計算候補は0。50点はv18取得済みの完全属性道路を再利用し、12点は新たに完全属性を取得。trunk近傍でも徒歩通行根拠がない道を歩行用に変換しない。30mを超える原点を動かさない。", f"今回の新規確認原点のうち未計算{summary['new_uncomputed_walks']}。全indexの未計算合計は{summary['total_uncomputed_index_entries']}。新たに確認した別原点の計算を128地点の減少として数えない。",'', '保留・未処理を明示：','- 船木鉄道の今回観測対象の保留原点はsentetsu-v19-20260915/ledger.jsonに原IDごとの区間候補・分岐・左右余裕等を記録。赤崎神社は方面と原座標は得られたが、前後停車原点が同じ分岐のない経路区間へ一意に対応せず保留。','- 船木鉄道の観測対象外の別路線・別曜日、および新しく取得したいわくにバス238原点の全件照合は未処理（岩国市229、県外等の境界対応保留9）。additional-original-inventory.jsonに市町別・原ID別で明示。県内の全保留を今回で解消したとはしない。','- 和木駅：公式Notion時刻表ページを確認。位置付きExcelはMicrosoftログインを要求し未取得。公式リンク先GTFS ZIPは取得できたが、和木を含む停留所名0・shapes.txtなしでW1の対応解消には不足。市公式2026公共交通マップの実画像には個別原ID付き位置対応はない。','- 防長交通：別の公式停留所検索は方面文言を確認できたが、地図原座標は取得403。国の代表点を方向別へ変換しない。','- 既存参考計算の対応保留は残り46原点。明示歩道ではない接続や別道路への対応を個別に確認する資料が必要。','- 長府A、宇部位置候補、由宇等の既存保留・v15訂正を維持。','', '## 検証・作業時間・保存','',f"実測{mins:.1f}分（timing.jsonの開始からこの実装記録まで、冒頭環境確認を除く）。新規徒歩計算は初回5原点70.7秒、追加2原点75.8秒、計146.5秒。各回の根拠グラフを保存。配信・保存時間は別添レシート。",'対象の原本一致・旧index保持・出典対応とアプリ関数テストを実施。新規7原点は保存グラフから再生成してバイト単位一致を確認（アプリ原本への上書きなし）。型検査・配信ビルド完了。今回の実ブラウザー・スマホ実機・Safari・現地は未検証。関数検証を実画面検証とはしない。','既存本人限定Sitesへ反映し、案件Driveへ変更ソース・追加根拠・台帳・配信物を保存する。実行済みの結果は配信保存レシートを参照。v18原本ZIPを再梱包せず、v18に適用できる差分と再開手順を保存。']
(D/'implementation-report.md').write_text('\n'.join(lines)+'\n')
print(summary)
