import fs from 'node:fs';
import path from 'node:path';
const root='dist';
const files=fs.readdirSync(root,{recursive:true}).filter(f=>fs.statSync(path.join(root,f)).isFile());
for(const f of files){
 if(!/^(index\.html|review\.html|about\.html|third-party-notices\.txt|data\/(bus_stop|shopping|review-stops)\.geojson|data\/(walking-onoda|review-routes|walk-release|walk-unreachable)\.json|data\/walk\/[\w.-]+\.json|assets\/[\w.-]+\.(js|css|png))$/.test(f.replaceAll('\\','/'))) throw Error(`Unexpected release file: ${f}`);
}
for(const file of ['index.html','about.html','third-party-notices.txt','data/bus_stop.geojson','data/shopping.geojson','data/walking-onoda.json','data/walk-unreachable.json','data/walk-release.json','data/walk/index.json']) if(!files.includes(file)&&!files.includes(file.replaceAll('/','\\')))throw Error(`Missing release file ${file}`);
const html=fs.readFileSync('dist/index.html','utf8');
for(const m of html.matchAll(/(?:src|href)="(\.\/assets\/[^"#]+)"/g)) if(!fs.existsSync(path.join(root,m[1])))throw Error(`Missing asset ${m[1]}`);
if(/(?:src|href)="\/assets\//.test(html))throw Error('Absolute asset path prevents subdirectory deployment');
for(const file of ['bus_stop.geojson','shopping.geojson','walk-unreachable.json']) if(!fs.readFileSync(`public/data/${file}`).equals(fs.readFileSync(`dist/data/${file}`)))throw Error(`Stale data: ${file}`);
if(!fs.readFileSync('public/data/walking-onoda.json').equals(fs.readFileSync('dist/data/walking-onoda.json')))throw Error('Stale walking graph');
const walkManifest=JSON.parse(fs.readFileSync('public/data/walk-release.json','utf8'));
const bakedCatchments=JSON.parse(fs.readFileSync('dist/data/walk/index.json','utf8'));
if(bakedCatchments.length!==walkManifest.count)throw Error(`Catchment count ${bakedCatchments.length} != manifest ${walkManifest.count}`);
for(const id of bakedCatchments) if(!files.includes(`data/walk/${id}.json`)&&!files.includes(`data\\walk\\${id}.json`))throw Error(`Missing catchment ${id}`);
const bus=JSON.parse(fs.readFileSync('dist/data/bus_stop.geojson','utf8'));
if(bus.features.length!==3946)throw Error('Unexpected bus stop count');
console.log(`Release verified: ${files.length} files; 3946 bus stops; source data matches dist.`);
const official=JSON.parse(fs.readFileSync('dist/data/review-stops.geojson','utf8'));
const routes=JSON.parse(fs.readFileSync('dist/data/review-routes.json','utf8'));
if(official.features.length!==907||new Set(official.features.map(f=>f.id)).size!==907)throw Error('Review stop count/IDs');
for(const [city,count] of [['hikari',172],['iwakuni',735]])if(official.features.filter(f=>f.properties.source_namespace===city).length!==count)throw Error(`Review count: ${city}`);
const routeIds=new Set(routes.map(r=>r.id));
if(official.features.some(f=>f.properties.stale_route_warning||f.properties.publication_status!=='ready-as-separate-source-layer'||f.properties.license!=='CC-BY-4.0'||f.properties.route_ids.some(id=>!routeIds.has(id))))throw Error('Invalid review candidate');
for(const file of ['review-stops.geojson','review-routes.json'])if(!fs.readFileSync(`public/data/${file}`).equals(fs.readFileSync(`dist/data/${file}`)))throw Error(`Stale review data ${file}`);
const review=fs.readFileSync('dist/review.html','utf8');
for(const m of review.matchAll(/(?:src|href)="(\.\/assets\/[^"#]+)"/g))if(!fs.existsSync(path.join(root,m[1])))throw Error(`Missing review asset ${m[1]}`);
console.log('Review verified: Hikari 172 + Iwakuni 735; excluded known stale routes; route references valid.');
